#!/usr/bin/env bash
set -ex
rm -rf dist/*

esbuild ts/index.tsx --outdir=dist --bundle --sourcemap \
  --entry-names=[dir]/[name]-[hash]

cd dist

cp ../index.html .
cp ../index.css .

mvhash() {
  hash=$(sha256sum "$1")
  hash=$(echo "$hash" | head -c 8)
  name=$(echo "$1" | sed "s/\./-$hash./")
  mv "$1" "$name"
}

cp ../zig-out/lib/wisp.wasm .
mvhash wisp.wasm

mvhash index.css
result=$(ls index*.css)
sed -i.bak -e "s|index.css|$result|" index.html

result=$(ls wisp*.wasm)
sed -i.bak -e "s|wisp.wasm|$result|" index.html

result=$(ls index*.js)
sed -i.bak -e "s|index.js|$result|" index.html
