#+bibliography: bibliography.bib

#+BEGIN_EXAMPLE
         █     █░ ██▓  ██████  ██▓███
        ▓█░ █ ░█░▓██▒▒██    ▒ ▓██░  ██▒
        ▒█░ █ ░█ ▒██▒░ ▓██▄   ▓██░ ██▓▒
        ░█░ █ ░█ ░██░  ▒   ██▒▒██▄█▓▒ ▒
        ░░██▒██▓ ░██░▒██████▒▒▒██▒ ░  ░
        ░ ▓░▒ ▒  ░▓  ▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░
          ▒ ░ ░   ▒ ░░ ░▒  ░ ░░▒ ░
          ░   ░   ▒ ░░  ░  ░  ░░
            ░     ░        ░
#+END_EXAMPLE

*Wisp* is a Lisp system for [[https://webassembly.org][WebAssembly]] and native execution.

It aims to offer an unusually pleasant developer experience
both while hacking and in production, though it's still /very
immature/ and far from ready for any serious use.

You can try the live browser-based IDE at [[https://wisp.town][Wisp.Town]].

Feel free to join the [[https://discord.gg/BeKtM3x687][Wisp Discord chat]] if you're interested
in following the development work, hacking on the system, or
chatting about Lisp, WebAssembly, and Zig.

Wisp has:

  - a browser-based IDE for live hacking and interactive
    debugging;

  - saving and loading of full system state images, including
    debugger state, also in browser local storage;

  - thoughtful integration with the browser environment, Node,
    Deno, and Unix in general;

  - first-class delimited continuations for advanced control
    flow;

  - interactive restartable conditions in the style of Common
    Lisp;

  - first-class stepwise execution for custom debuggers,
    schedulers, etc;

  - sandboxed execution with fine-grained capabilities via
    WebAssembly;

  - an implementation written in [[https://ziglang.org][Zig]];

  - and more!


How to hack on Wisp (written by a visitor):

  - Wisp uses the nightly version of Zig. I used
    `brew install zig --HEAD`. There is probably a similar
    command for your system's package manager. You might
    also want to look at [[https://github.com/ziglang/zig-bootstrap][zig-bootstrap]].

  - You should be able to run `make` to build the web thing.
    - It looks like you need to `cd web && npm i` first.
    - You might need to serve the directory with something
      like `npx http-server --cors` to bypass CORS.

  - Make will put the `wisp` binary at `core/zig-out/bin/wisp`.

  - Now you can edit `core/lisp/test.wisp` and run
    `./core/zig-out/bin/wisp run core/lisp/test.wisp`.

* Local Variables :noexport:
  Local Variables:
  fill-column: 62
  End:
